### ISSUE TITLE
Lvis checkpoint

### ISSUE THREAD

**Issue by jihwanp** [jozhang97/DETA#2]
Hi I wonder if you have a plan to provide the checkpoint file of LVIS.

Thanks

**Comment by jozhang97** [comment]
No.

The impl with LVIS is straight forward and I am happy to assist with any issues along the way.
We simply took Detic from https://github.com/facebookresearch/Detic, changed the third_party/deformable_detr to deta and added some detectron2 configs (assign first, assign second, balance_k) and NMS.
