### ISSUE TITLE
first stage assignments thershold

### ISSUE THREAD

**Issue by SangbumChoi** [jozhang97/DETA#25]
Hi, in your paper it says. We use a threshold 0.7 for the first stage.

but your [code](https://github.com/jozhang97/DETA/blob/985fa0b7afbbd86db6f907ff3a855828947ff631/models/deformable_transformer.py#L192) seems to use 0.9.

Also, is there any specific reason for [keep top Q/L indices for L levels instead of ignoring the ratio](https://github.com/jozhang97/DETA/blob/985fa0b7afbbd86db6f907ff3a855828947ff631/models/deformable_transformer.py#L199)?
Thanks

**Comment by jozhang97** [comment]
Thanks for pointing this out, we will update the paper.

Keeping the top Q/L makes sure each level has the same number of proposals per level. There is no specific reason besides it seems to work

**Comment by SangbumChoi** [comment]
Thanks for the reply!
