### ISSUE TITLE
Swin-L config without Objects365 pretraining and Objects365 pretraining setting

### ISSUE THREAD

**Issue by jay-lcchen** [jozhang97/DETA#28]
Hello,

Thank you for sharing the great work! We really find it useful.

We have one question regarding how to train your model using Swin-L, without Objects365 pretraining (i.e, only ImageNet-21K pretraining). Do you mind sharing the config or any settings for us to try?

Additionally, the script to pretrain the Swin-L on Objects365 (deta_swin_pre.sh) is missing. Is it also possible that you can share that script and Objects365's setting (e.g., all images are used? and so on?).

Thanks,

**Comment by jozhang97** [comment]
Hi Jay,

I'm glad you like the work!

1. Swin-L without Objects365 pretraining: we have not tried this, but I think you can just replace the Objects365 checkpoint with the IN21K checkpoint from https://github.com/microsoft/Swin-Transformer 
2. the script to pretrain the Swin-L on Objects365: We trained on Objects365 training set (no merge with val) on 24epoch schedule (details in the paper). The only change to the code are increasing num_classes and training with higher resolution images. Happy to answer any other questions I can.

**Comment by jay-lcchen** [comment]
Awesome. Thank you, Jeffrey, for the quick response and for the clarification.
It is clear to me and we will run the experiments as suggested and see how it goes. 

Thanks,
