### ISSUE TITLE
How to infer on an image?

### ISSUE THREAD

**Issue by luckcodingdog** [jozhang97/DETA#9]
Thank you for your great work!
Is there any script to infer on an image with your model?

**Comment by jozhang97** [comment]
Thanks for your interest!
I haven't written one myself but the nice people at HuggingFace (Niels) prepared one [here](https://colab.research.google.com/drive/1epI4ejrD0dbrSR9vRRhEPE7duoALqIk9?usp=sharing)
See this github issue https://github.com/jozhang97/DETA/issues/3

**Comment by luckcodingdog** [comment]
Thanks for your answer.
I have tried this idea, but it run on the cpu not gpu.
The speed of inference is very slow.

**Comment by xinlin-xiao** [comment]
> Thanks for your answer. I have test the same script from Niels' github: https://github.com/NielsRogge/Transformers-Tutorials/blob/master/DETA/Inference_with_DETA_(ResNet_%2B_Swin_backbones).ipynb It run on cpu not gpu. If someone wants to test on gpu, he should add lines like below: `device = "cuda" if torch.cuda.is_available() else "cpu"` `model.to(device)` `inputs = inputs.to(device)`

@luckcodingdog Hello， Where can I add these lines：
`device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)
inputs = inputs.to(device)`
